spring.application.name=marketplace
server.port=4002
spring.datasource.url=jdbc:mysql://localhost:3306/marketplace
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.datasource.username=root
# poner su clave de mysql
spring.datasource.password=thomaspacheco
spring.jpa.hibernate.ddl-auto=update
application.security.jwt.secretKey=36EFE8310D5B6A84827599D9EAD993D73767A9D36507D806FA9EA5FFB5F8E338E6865E609D5AEB5C3660510E6A5B6030BEC54899813E5FD58E2EDD46658EF4D7
application.security.jwt.expiration=86400000